# Generated by Django 3.2.8 on 2021-10-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_am'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='am',
            new_name='registration_number',
        ),
    ]
